### ISSUE TITLE
Implement conversion to PISA files

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#106]
Based on our discussion at the 7 December 2021 GNN developer meeting, it would be brilliant to have this functionality implemented in the repo. With #96 we should be able to train on Upgrade MC, and in #83 we added the functionality to export GNN models as `I3Modules` so the conversion to PISA files would be an important step to allow us to produce analysis-level outputs from the repo.

@mhaminh, would you have time to look into this? Or do you have some existing PISA (conversion) code that I could build off of, to include similar functionality in the repo?

**Comment by RasmusOrsoe** [comment]
@asogaard I think we can close this once #180 is accepted
