### ISSUE TITLE
Enable constructing graphs from multiple pulsemaps

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#107]
In the context of e.g. IceCube Upgrade, it will be necessary to combine distinct pulsemaps (e.g. `I3RecoPulseSeriesMapRFCleaned_mDOM` and `SRTInIcePulsesTWSRT`), that cover disjoint sets of DOMs, into a single graph representing each event. The most direct way to do this would be to allow for multiple pulsemaps to be given as argument to `SQLiteDataset`[here](https://github.com/icecube/graphnet/blob/5a91f7425855c037a7b0e6419f76a9ae926a6816/src/gnn_reco/data/sqlite_dataset.py#L8) and then concatenate the resulting features from each pulsemap.

**Comment by RasmusOrsoe** [comment]
@asogaard its likely that the upgrade people will provide a single pulsemap for cleaned events in the future. fyi

**Comment by asogaard** [comment]
Cool, in that case we can park this until we see whether it will actually be relevant.
