### ISSUE TITLE
Implement node classification

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#110]
Currently, the repo support binary graph-level classification. However, for tasks like hit clearning, node-level classification would be relevant.

**Comment by asogaard** [comment]
@RasmusOrsoe one question here: GNNs generally have a number of message-passing layers and local node updates (using MLPs) followed by a global pooling operations (sum, max, avg) and a number of densely connected layers. This is true for the `DynEdge` class, for instance. However, if we want to use the same base GNN architecture (e.g. DynEdge) for node-level predictions we would need to drop the global pooling. I see two ways of doing this:

1. Either we subdivide the current `GNN` class into a message-passing component and a pooling component; then graph-level predictions will use both while node-level predictions will only use the former.
2. Implement separate GNN classes for each type of prediction, i.e. writing a separate `DynEdge`-like class but without the global pooling and subsequent layers.

There may also be other options. Of these two, I would probably vote for (1.) as (2.) involves essentially writing each GNN architecture twice. What do you think?

**Comment by RasmusOrsoe** [comment]
I'd prefer 2) as that means no changes to the sensitive code for the paper. Further down the road we could do something fancy like 1).

Rasmus

**Comment by asogaard** [comment]
But the paper code is separate from this, right? This does not affect `paper_branch`. 🙂

**Comment by asogaard** [comment]
I figure we can close this following #190, where approach (2.) above has been followed.
