### ISSUE TITLE
How should we represent/record standard dataset?

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#112]
In the interest of reproducibility, benchmarking, and such it could be useful to have simple "cards" that unambiguously define various benchmark datasets. This could be in the form of a simple structure like:
```
datasets/
|-- upgrade-sensitivity-mc.yml
|-- deepcore-doublebang-mc.yml
|-- deepcore-oscillations-2021-data.yml
`-- (...)
```
with each YAML file containing little more than path(s) to I3 files on Cobalt.

What do y'all think?

**Comment by philippeller** [comment]
sounds reasonable to me
