### ISSUE TITLE
Create SQLite database from MC files

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#131]
Depends on #129. This is only necessary if we will be training new GNN models on this Level 2 data.

**Comment by BozianuLeon** [comment]
I am working on this issue, specifically covering the creation of level2 MC databases from relevant i3 files. Will happily assign myself and liaise with others.

**Comment by asogaard** [comment]
Hi @BozianuLeon, I believe this has been done. Could you confirm, and if so, document the outcome and close the issue? Or is it waiting on #178?
