### ISSUE TITLE
Prepare muon vs. neutrino event classifier model

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#133]
As discussed with @troelspetersen, the muon classifier may output information related to stopping position meaning that a dedicated down-stream stopped vs. through-going muon classifier may not be necessary. Therefore, such a classifier has been left out of the project initially.

**Comment by asogaard** [comment]
Hi @BozianuLeon, has this classifier model been prepared for running on Level-2 data?

**Comment by BozianuLeon** [comment]
Yes, as part of the real data campaign @kaareendrup and I have trained models for noise/particle, neutrino/muon and stopped/through classifiers on level 2 simulated data.
I would say that while it is possible to reconstruct the stopping position of these muons we do not (yet) have a trained model for this. Though it would be a trivial task to acquire one. 
However, for this issue we can consider the matter resolved.
