### ISSUE TITLE
Prepare neutrino PID (track/cascade) event classifier model

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#134]

**Comment by asogaard** [comment]
Hi @BozianuLeon, has this classifier model been prepared for running on Level-2 data?

**Comment by BozianuLeon** [comment]
This is actually in the to-do list for @kaareendrup and I. We just need GPU time to train on a ready-made level 2 database.

**Comment by kaareendrup** [comment]
This is now up and running!
