### ISSUE TITLE
Update installation instruction

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#211]
Currently we have minimal installation instructions that generally works, but often leads to the odd bug. By suggestion from @MortenHolmRep, we should update our installation process to be simple, robust, and reproducible and document it adequately. This includes considering:

- [ ] Should we use conda _and_ pip?
- [ ] Can we install pytorch and pytorch-geometric at the same time?
- [ ] Should we expand package version requirements to ranges rather than exact ones?
- [ ] Should we provide a `requirements.txt` file? And how would this complement the requirements in `setup.py`?

**Comment by MortenHolmRep** [comment]
1) I think the [pip vs conda](https://stackoverflow.com/questions/20994716/what-is-the-difference-between-pip-and-conda) discussion is out of my competance level
2) Can this be done sequentially in the setup.py script? Like it is currently done for pytorch
3) I think [version specifiers](https://peps.python.org/pep-0440/#version-specifiers) would be a good way to go about it when we specify it as a requirement for the [installation](https://pip.pypa.io/en/stable/cli/pip_install/)?
4) I think the requirements.txt complements the setup.py, in that [we can call as part of the setup process](https://stackoverflow.com/questions/46419607/how-to-automatically-install-required-packages-from-a-python-script-as-necessary)
