### ISSUE TITLE
Cannot reconstruct 'Data' object from 'Batch' because 'Batch' was not created via 'Batch.from_data_list()'

### ISSUE THREAD

**Issue by RasmusOrsoe** [icecube/graphnet#264]
The output of our coarsening methods are not compatible with `Batch.to_data_list()`. Below is a minimal working example of the issue.

```
import torch
import numpy as np
from graphnet.models.coarsening import DOMCoarsening
from graphnet.data.constants import FEATURES, TRUTH
from graphnet.data.sqlite.sqlite_selection import (
    get_equal_proportion_neutrino_indices,
)

from graphnet.models.training.utils import (
    make_train_validation_dataloader,
)
from graphnet.utilities.logging import get_logger

logger = get_logger()

# Configurations
torch.multiprocessing.set_sharing_strategy("file_system")

# Constants
features = FEATURES.DEEPCORE
truth = TRUTH.DEEPCORE[:-1]

# Main function definition
def main():
    # Configuration
    config = {
        "db": "/remote/ceph/user/o/oersoe/databases/dev_lvl7_robustness_muon_neutrino_0000/data/dev_lvl7_robustness_muon_neutrino_0000.db",
        "pulsemap": "SRTTWOfflinePulsesDC",
        "batch_size": 100,
        "num_workers": 10,
        "gpus": [1],
        "target": "energy",
        "n_epochs": 2,
    }
    # Common variables
    train_selection = np.arange(0,1000,1).tolist()

    (
        training_dataloader,
        validation_dataloader,
    ) = make_train_validation_dataloader(
        config["db"],
        train_selection,
        config["pulsemap"],
        features,
        truth,
        batch_size=config["batch_size"],
        num_workers=config["num_workers"],
    )

    # Coarsening
    coarsening = DOMCoarsening(reduce = 'min')

    # get a batch
    batch = next(iter(training_dataloader))

    # apply coarsening
    pooled_batch = coarsening(batch)

    # Split to data_list
    pooled_batch.to_data_list()
    
# Main function call
if __name__ == "__main__":
    main()
```

**Comment by RasmusOrsoe** [comment]
@asogaard my impression was that this issue was fixed. Can you confirm that this is unintended behavior? The new GNN that i'm working on uses this functionality quite a lot - and I would like to use your coarsening along with it. So it would be a bummer if it's truly incompatible!

**Comment by asogaard** [comment]
Hi @RasmusOrsoe,
There was a bug raised by @mhaminh (#235) that related to the same problem you're encountering here. Martin's problem was addressed in #245 by changing how we extract feature names from the `Detector` class such that we didn't rely on indexing `Batch` at all; it was a work-around. That is why you're still running into this problem, and it is not unexpected behaviour as such. But we could certainly improve on the current pooling in pytorch-geometric such that we can always index a `Batch`, even after it's been pooled. I think that would be a very nice option to have. But if you're planning on training models that rely on splitting and re-batching events,  my experience with #245 tells me that this is likely to be prohibitively slow, and the best solution might be to find a solution that works with the `Batch` as it is.

**Comment by RasmusOrsoe** [comment]
I have developed a fix for the issue. Here is a minimalistic example:

**Comment by asogaard** [comment]
Yes, I think the above makes total sense: Adding the functionality in `add_slice_dict` and `add_inc_dict` to the bottom of `Coarsening.__call__` would ensure that we are always returning a "complete" `Batch` object without having to decompose and reassemble it. I think that would be very elegant! I can't judge whether the functionality in `add_slice_dict` does what's required, so perhaps we should add a unit test that shows that `batch[ix]` after pooling corresponds to the same event as `batch[ix]` before pooling. But please go ahead with a PR, I think this is very promising! 🎉
