### ISSUE TITLE
trouble running scripts after clean install 

### ISSUE THREAD

**Issue by MoustHolmes** [icecube/graphnet#268]
**Describe the bug**
I encounter `Illegal instruction (core dumped)` when running any script after clean install of graphnet.

**To Reproduce**
1. installed miniconda; following the installation method specified at "URL"
2. installed graphnet; following the specified steps on the github README for standalone
3. First tried adding `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/anaconda3/lib/` to .bashrc
4. Also tried adding these lines to bashrc 
```export LD_LIBRARY_PATH=~/anaconda3/lib:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-11/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-11/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/anaconda3/lib/
```
5. Activated environment 
6. Run `python train_model.py`
7. Get error `Illegal instruction (core dumped)`

**Comment by asogaard** [comment]
Hi @MoustHolmes,

Thanks for raising this issue! Where are you installing and running the package? That is, on the HEP machine? If so, which one?

**Comment by MortenHolmRep** [comment]
Moust is away about a week (if I recall correctly), so I will attempt to answer.
I have instructed a similar set up for all the new students. The setup should match that of Peter and the others.
We have been using hep01 and hep04.

**Comment by asogaard** [comment]
Hi @MortenHolmRep  and @MoustHolmes,
In your own time, could you confirm whether this issue persist when following the new instructions in the README, updated based on #267?

**Comment by MoustHolmes** [comment]
It works now however I'm not sure where the fix was.
