### ISSUE TITLE
installing in cvmfs without torch for file conversion  - conversion fails because torch is not installed

### ISSUE THREAD

**Issue by RasmusOrsoe** [icecube/graphnet#269]
**Describe the bug**
We offer to install graphnet without ML dependencies for file conversion. If one does so, file conversion fails because said dependencies are not installed. 

**To Reproduce**
1. Follow installation instructions for graphnet in cvmfs without torch
2. Run the i3->sqlite conversion example
```
(databaseprod) [pcs557@hep03 tools]$ python make_many_databases.py
graphnet: INFO     2022-08-29 19:23:50 - get_logger - Writing log to logs/graphnet_20220829-192350.log
Traceback (most recent call last):
  File "make_many_databases.py", line 13, in <module>
    from graphnet.data.sqlite.sqlite_dataconverter import SQLiteDataConverter
  File "/lustre/hpc/hep/pcs557/github/graphnet/src/graphnet/data/sqlite/__init__.py", line 2, in <module>
    from .sqlite_dataset import SQLiteDataset
  File "/lustre/hpc/hep/pcs557/github/graphnet/src/graphnet/data/sqlite/sqlite_dataset.py", line 5, in <module>
    from graphnet.data.dataset import Dataset, ColumnMissingException
  File "/lustre/hpc/hep/pcs557/github/graphnet/src/graphnet/data/dataset.py", line 6, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

**Comment by asogaard** [comment]
Thanks for raising this issue, @RasmusOrsoe!

I will either:
* make all `torch` imports fully optional within the `graphnet.data` module, or
* make sure that importing e.g. `SQLiteDataConverter` — which doesn't require `torch` — does not trigger an import of e.g. `SQLiteDataset` which _does_ require `torch` as is used at a different point in the workflow.
