### ISSUE TITLE
Write GNN predictions to Upgrade I3 files

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#48]
Is blocked by #46 and #47

**Comment by RasmusOrsoe** [comment]
@RasmusOrsoe  will provide example code

**Comment by asogaard** [comment]
As agreed at today's meeting I'll just tag @mhaminh. We agreed that Martin will focus on just getting the GNN predictions (using code outside of this repo) into PISA for the sensitivity studies. Once that it is in a good place, we Martin and I will discuss how to best updating the repo code accordingly to support these studies.
