### ISSUE TITLE
Permute input parameters of main models to quantify sensitivity (alá Mirco) for the robustness section

### ISSUE THREAD

**Issue by RasmusOrsoe** [icecube/graphnet#60]
sample random epsilon from a normal distribution that covers an appropriate range and permute input parameters with it. (One permuted input variable pr. test to establish causality). E.g.

`dom_t -> dom_t + epsilon`  where epsilon is sample from a normal distribution covering +-3ns

Save results in our current format and give to Rasmus

**Comment by asogaard** [comment]
As agreed at today's meeting I'll just tag @mhaminh

**Comment by RasmusOrsoe** [comment]
@asogaard sorry - yes this is done.
