### ISSUE TITLE
Set up automated workflow for building, publishing docker images

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#84]
This would provide a fully self-contained OS that is built for each tagged release of graphnet and has all dependencies pre-installed. Furthermore, these images could form the basis for a graphnet metaproject environment in singularity, which should make setup trivial on all systems with a CVMFS mount.

**Comment by asogaard** [comment]
cc @RasmusOrsoe @MortenHolmRep: Considering the hassle with #212, #208 etc., I'll probably take this up to make setup as easy as `$ /cvmfs/icecube.opensciencegrid.org/<...>/graphnet/env-shell.sh`

**Comment by RasmusOrsoe** [comment]
@asogaard hey - I think that would be a great idea. But one thing to keep in mind; will users from other experiments have access to cvmfs? Is it open source?

Also; to which extent does cvmfs support gpu learning? I think the hurdle here is how the image will be run on workstation with different gpu hardware and therefore different cuda versions etc. 

Just a few thoughts...

**Comment by asogaard** [comment]
Good points, Rasmus!
* Installing it in the IceCube CVMFS (as is intended) would probably mean that it would be IceCube-only. We would still support generic python installation (that's what @MortenHolmRep is streamlining). This other option would simply be a quality of life offering for IceCubers, meant to remove all barriers to entry.
* You are right that we should consider building separate cpu, cuXYZ images, unless we could find some baseline (not cutting-edge) CUDA driver version that works on non-GPU machines and that is compatible with all of the torch(-geometric) versions that we are supporting. I'll look into this!
