### ISSUE TITLE
Implement a Euclidean graph builder

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#91]
See https://github.com/icecube/gnn-reco/blob/main/src/gnn_reco/models/graph_builders.py

**Comment by BozianuLeon** [comment]
Hi Andreas I know I have spoken about looking into KNN alternatives. I'd like to tackle this issue and maybe look at other graph builders. Do you have a link to the Euclidean graph builder paper you mentioned previously. Thanks

**Comment by asogaard** [comment]
Hi @BozianuLeon!
That sounds brilliant. 👏   You could look to https://arxiv.org/abs/1809.06166 for inspiration. Sec. IV, item (b) describes how they construct graphs, where `d_{ij}` is the Gaussian kernel over the Euclidean distance between DOMs `i` and `j`, and `a_{ij}` is the normalised node adjacency based on this measure. Let me know if we should have a chat about implementation details. :)
