### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by asogaard** [icecube/graphnet#93]
As agreed at the weekly developer meeting on 7 December, we will rename the repo and the contained python package to "GraphNeT" (in plain text writing), short for _Graph neural networks for neutrino telescope event reconstruction_ / `graphnet` (in code, file names, package name, etc.). This will require (1) changing the repo name in the settings and (2) changing names across code files. @philippeller, as the owner of the repo, is the only one who can do the first item; I will prepare a single, comprehensive PR for the second item.

**Comment by philippeller** [comment]
repo renamed
